version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fafnir-nextjs-todo
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://fafnir_admin:fafnir_secure_password_2026@172.17.0.1:5432/todolist_db?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
